{% set name = "python-constraint" %}
{% set version = "1.4.0" %}
{% set sha256 = "501d6f17afe0032dfc6ea6c0f8acc12e44f992733f00e8538961031ef27ccb8e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip

  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - constraint

about:
  home: http://labix.org/python-constraint
  license: BSD-2-Clause
  license_family: BSD
  license_file: setup.py
  summary: 'Python module for handling Constraint Solving Problems'
  description: |
    The Python constraint module offers solvers for Constraint Solving Problems
    (CSPs) over finite domains in simple and pure Python. CSP is class of
    problems which may be represented in terms of variables (a, b, ...),
    domains (a in [1, 2, 3], ...), and constraints (a < b, ...).
  doc_url: http://labix.org/doc/constraint/
  dev_url: https://github.com/python-constraint/python-constraint

extra:
  recipe-maintainers:
    - stuertz
